[package]
name = "libcec-sys"
version = "0.1.0"
authors = ["Sami Salonen"]
edition = "2018"
license = "GPL-2.0"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]

[build-dependencies]
cmake = "0.1.42"
fs_extra = "1.1.0"
