# docker images referenced here are built in ci/script.sh

[target.x86_64-unknown-linux-gnu]
image = "cross-libcec-sys:x86_64-unknown-linux-gnu-0.1.16"

[target.armv7-unknown-linux-gnueabihf]
image = "cross-libcec-sys:armv7-unknown-linux-gnueabihf-0.1.16"