name: Continuous Deployment

on:
    push:
        tags:
            - "[0-9]+.[0-9]+.[0-9]+"

jobs:
    publish-cargo:
        name: Publishing to Cargo
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Checkout submodules
              shell: bash
              # basically git submodule update --init --recursive but replacing git@github.com with https
              # for anonymous checkout
              run: |
                  git submodule update --init
                  git submodule foreach --recursive '
                  echo "pwd: $(pwd)" ; \
                  if [ -f .gitmodules ]; then \
                      ( sed -i "s/git@github.com:/https:\/\/github.com\//" .gitmodules \
                      && git submodule sync --recursive ) ; \
                  fi ; \
                  git submodule update --init \
                  ;'
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  profile: minimal
                  override: true
            - uses: actions-rs/cargo@v1
              with:
                  command: publish
                  use-cross: true
                  args: --target x86_64-unknown-linux-gnu --token ${{ secrets.CARGO_API_KEY }} --allow-dirty
