on: [push, pull_request]
name: Continuous Integration

jobs:
    test:
        name: Test Suite ${{ matrix.job.os }}
        runs-on: ${{ matrix.job.os }}
        strategy:
            matrix:
                rust: [stable]
                job:
                    - os: ubuntu-latest
                      os-name: linux
                      target: aarch64-unknown-linux-gnu
                      use-cross: true
                    - os: ubuntu-latest
                      os-name: linux
                      target: i686-unknown-linux-gnu
                      use-cross: true
                    - os: ubuntu-latest
                      os-name: linux
                      target: arm-unknown-linux-gnueabi
                      use-cross: true
                    - os: ubuntu-latest
                      os-name: linux
                      target: armv7-unknown-linux-gnueabi
                      use-cross: true
                    - os: ubuntu-latest
                      os-name: linux
                      target: mips-unknown-linux-gnueabi
                      use-cross: true
                    - os: ubuntu-latest
                      os-name: linux
                      target: mips64-unknown-linux-gnueabi64
                      use-cross: true
                    - os: ubuntu-latest
                      os-name: linux
                      target: mips64el-unknown-linux-gnueabi64
                      use-cross: true
                    - os: ubuntu-latest
                      os-name: linux
                      target: mipsel-unknown-linux-gnueabi
                      use-cross: true
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Installing Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: ${{ matrix.rust }}
                  profile: minimal
                  override: true
            - name: Cargo test
              uses: actions-rs/cargo@v1
              with:
                  command: test
                  use-cross: ${{ matrix.job.use-cross }}
                  toolchain: ${{ matrix.rust }}
                  args: --target ${{ matrix.job.target }}

    rustfmt:
        name: Rustfmt
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  profile: minimal
                  override: true
                  components: rustfmt
            - name: Check formatting
              uses: actions-rs/cargo@v1
              with:
                  command: fmt
                  args: --all -- --check

    clippy:
        name: Clippy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  profile: minimal
                  override: true
                  components: clippy
            - name: Clippy Check
              uses: actions-rs/cargo@v1
              with:
                  command: clippy
                  args: -- -D warnings

    coverage:
        name: Code coverage
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Install stable toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  prifile: minimal
                  override: true
            - name: Run cargo-tarpaulin
              uses: actions-rs/tarpaulin@v0.1
              with:
                  args: "--ignore-tests --out Lcov"
            - name: Upload to Coveralls
              # upload only if push
              if: ${{ github.event_name == 'push' }}
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  path-to-lcov: "./lcov.info"
